### ISSUE TITLE
Can `DerivedVar` support `map/update` semantics in addition to `map/contramap` semantics?

### ISSUE THREAD

**Issue by olynch** [raquo/Airstream#104]
Very often I have a situation where I want to update a small part of a large data structure contained in a `Var`. I.e., I have a function `A => B` and a function `(A,B) => A`, but no function `B => A` because `B` is too small. Is there a technical reason why `DerivedVar` couldn't be implemented in this way, or is there something else in Laminar that works in this way?

**Comment by raquo** [comment]
I think my original intent was to simply use `parentVar.now()` in the `B => A` function to get the current `A`.

It does seem that providing current `A` by changing `zoomOut` from `B => A` to `(A, B) => A` is a good idea :+1:.

It's a pretty small change, implementation-wise, so I'll try to add this after I finish everything else in the next version.

**Comment by olynch** [comment]
:fireworks: :fireworks: Thanks @raquo, this is awesome!
