### ISSUE TITLE
idiomatic usage of foreach for EventStream

### ISSUE THREAD

**Issue by doofin** [raquo/Airstream#109]
I'm wondering the best way to use foreach method for EventStream(for logging ,etc). Currently I make a global owner for this which doesn't feel quite right, is there a better way?

**Comment by raquo** [comment]
Idiomatic usage is to have a system that manages the owners for you without
you needing to do it manually.

For example, if using Laminar, you generally don't use `foreach` on
streams, you use methods like `-->` and `<--` that create owner's as needed
behind the scenes (the lifetime of those owners match the lifetime of
corresponding DOM elements, roughly speaking).

**Comment by doofin** [comment]
Thanks, so it seems that I have to create owner and manage it by myself for this scenario

**Comment by raquo** [comment]
Yes, you can create instances of ManualOwner and similar types.
DynamicOwner might also be of interest to you, depending on how complex
your requirements are.

**Comment by doofin** [comment]
thanks!
