### ISSUE TITLE
Streams should emit in a shared transaction when starting

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#111]
# Problem description

Typically when a stream starts, it does not emit any events immediately, this happens later. For example, `parentStream.map(...)` does not emit anything on start (unless `parentStream` does), `FetchStream.get(...)` needs to wait for the response, etc.

However, some streams do emit events when they're [starting](https://github.com/raquo/Airstream/#laziness) (i.e. when they are getting their first subscriber), and that can cause arguably surprising behaviour. I don't remember running into that, recently at least, but here is a trivial example in Laminar:

```scala
val container = dom.document.getElementById("app-container")
val stream = EventStream.fromValue(1)
render(
  container,
  div(
    child.text <-- stream,
    child.text <-- stream.map(_ * 10)
  )
)
```
([scribble](https://scribble.ninja/u/raquo/ckhdwizgeisnwfdnzigzjxniempm))

You might expect the div to contain `1` and `10`, but actually it will only contain `1`. Why: because when the div is mounted, its subscriptions will be activated sequentially, one by one:

* First, `child.text <-- stream` will activate, this will start `stream`, and the stream will emit an event (`1`) in a new transaction. However, when this happened, we were not inside any other transaction, so the event has nothing to wait for, and will propagate immediately, being sent to child.text.

* Then, `child.text <-- stream.map(_ * 10)` will activate. The `stream.map(_ * 10)` stream will be started, and it will be added to the list of listeners on `stream`, but nothing else will happen, because `stream` is already started at this point, and the event that it emitted on start (`1`) has already been fully propagated – before this second subscription was activated. So, the stream `stream.map(_ * 10)` will not receive any events, and will not emit any events, and this second `child.text` will miss the event.

If `stream` was instead a signal, everything would have worked as you'd expect, because signals remember their current value, but streams by design have no concept of current value.

# Importance

I think this is undesirable for a couple reasons:

1. It's unintuitive and not obvious. Looking at the code, you wouldn't expect it. You would get the expected behaviour if you changed `val stream` to `def stream`, creating two identical but independent streams, but that's not the kind of finagling I want Laminar users to need to do.

2. Running this same code inside a transaction (e.g. rendering this div inside `child <-- someOtherStream.map(...)`) will produce different results: in that case, since the `1` event is emitted in a new transaction, that transaction will wait for the currently ongoing transaction to finish, and by the time this happens, both of the child.text subscriptions will have be added, so both of them will process that event.

# Scope

`EventStream.fromValue(1)` is just the most obvious case. Any stream that emits events immediately when it's starting is affected by this problem. Here's an exhaustive list of such streams, I think:
- CustomSource: any user-defined streams using this API can emit on start if the user chose so (these streams can also emit an error on start if the user's onStart function throws)
- EventStream.fromValue(1) and various aliases to it: by design
- PeriodicStream: calls tick() on start, which emits its current value
- x.flatten or x.flatMap Flattened / Flatmapped streams:
  - When using `ConcurrentStreamStrategy` manually, the stream emits an error on start when its parent is a signal in an error state
  - When flattening an `EventStream[Signal[A]]`, the resulting SwitchSignalStream emits the signal's updated value on start IF its value was updated while the stream was stopped. Much like signal.changes, except... well, more on that below.
- Signal.changes: emits a new value if the signal has changed its value while the stream was stopped (As of Airstream v15)

# Proposed solution

I mentioned `signal.changes`, but that one is different than the others, because in Airstream v15 I added special logic to it to handle something that is very similar to this problem, but is about re-starting those streams, not starting them for the first time. See the docs explaining _that_ problem [in this section](https://github.com/raquo/Airstream/#restarting-streams-that-depend-on-signals-signalchanges). Relevant quote:

> To avoid [the problem I mentioned], we have a special mechanism [for signal.changes] that lets us batch simultaneous events in a new transaction when restarting observables. Currently, it's only used to restart signal.changes. Basically, to avoid this restarting glitch, you want to wrap all your simultaneous observer additions into Transaction.onStart.shared { /* code here */ }, so any signal.changes you restart within that block will all emit in the same transaction. This is also not a perfect match for "normal" Airstream behaviour, and could potentially cause the other kind of FRP glitch where an intermediary event that you do expect to happen is swallowed by the system instead. However, of the two evils I think this is a lesser one, because it's much less common for that to be a problem. Ideally I would like to find a more robust mechanism for this edge case, but currently I lack the time required to do the research.

> Airstream's DynamicOwner uses this onStart.shared mechanism when activating all of its subscriptions, and all Laminar's methods like ~~Tag.apply and~~ amend do the same when applying multiple modifiers at a time, so you really shouldn't ever need to use onStart.shared manually, unless you're an advanced user creating your own custom modifiers or ownership primitives.

So, I think all of those streams listed above, that emit events when staring, need the same kind of treatment that I gave to `signal.changes` in Airstream v15 – the code in their `onStart` methods that creates a new transaction immediately, needs to instead schedule the new transaction to be executed at the end of the current `onStart.shared` block.

# Side effects

The proposed solution will result in our example executing as I would expect, the div containing both 1 and 10, that's good.

But it will also bring a more fundamental change: essentially, ALL of the events that are emitted like this – on start, or in Laminar, on mount – will now be treated as having had happened "at the same time", i.e. in the same transaction. On the surface, it seems like the right way to think about those events, since they all indeed had only one underlying event triggering them – the mounting – but the potential problem is, you normally wouldn't expect something like `stream` and `stream.flatMap(...)` to emit in the same transaction, regardless of what's inside `...`, but now, they could. It's a similar problem to what `signal.changes`, but that one is a bit more niche, because it only applies to **re-**starting that stream, whereas this will now apply to more types of streams, and also when starting them for the first time, not just re-starting.

As I work on this, I will come up with a couple test cases demonstrating the side effect, it's a bit too involved to do right now. I hope that this will not be a significant problem.

# What now

I'd like to know if you have encountered the problematic behaviour, and how surprising / annoying it was. For myself, I don't remember running into it, as I tend to use signals for anything that remotely resembles state, keeping streams only for things like user clicks for the most part, and those types of events just don't tend to happen on start / on mount.

I haven't started implementing this change yet, but I have a good idea of what needs to be done. If it actually works the way I think it will, I think the fix will be binary compatible, and I will release Airstream v16.0.1-M1, which you'll hopefully be able to try without updating any other dependencies. I don't want to publish a non-milestone 16.0.1 version because I don't want Scala Steward or other tooling suggesting it as a trivial update. I think "M1" should be enough to dissuade people anyway? If all is well then I'll eventually bring these changes into v17 a few months from now, but I do want a "preview" release that has nothing except these changes, to fish out any issues early on.

**Comment by yurique** [comment]
I don't remember having problems related to this, either. 
But I'm usually only using `.fromValue(..)` to "pre-start" some other stream of events (like in `EventStream.merge( fromValue( ... ), buttonClicksStream )`).
