### ISSUE TITLE
Error: code length overflow

### ISSUE THREAD

**Issue by FabioPinheiro** [raquo/Airstream#113]
I'm getting the error `code length overflow. (23676>23648)` AirstreamError.scala:75

This happens when setting a big string in a Var `Var[String](initial = ...)`

I think the error is not clear
Is there a way to mitigate this?

**Comment by raquo** [comment]
I don't think this error is coming from Airstream, I'm guessing it's from
some QR code library?

https://www.google.com/search?q=%22code+length+overflow%22

**Comment by FabioPinheiro** [comment]
oh I'm sorry about bothering you.
That's possible I'm using a QR code library with data from that `Var`.
But I was convinced that I commented all the signals from and to the `Var` before open this issue.

Let me do a little bit more testing.
Thank you
