### ISSUE TITLE
split doesn't memoize on Signal[LazyList[A]]

### ISSUE THREAD

**Issue by mattjacobus** [raquo/Airstream#117]
SplitSignal uses side effects in a map over the elements to keep track of which keys have been seen and since the LazyList is evaluated later, it believes no keys were seen and purges all the child signals and calls your project function on every event.  You might want another implicit specifically for LazyLists that does a force.

**Comment by raquo** [comment]
Thanks, good find! Somehow I've never used LazyList...

I think I'll update the `map` method of `ImmutableSeqSplittable` to do something special if the input is a LazyList. Probably convert it to a strict Seq like List or ArraySeq.

**Comment by raquo** [comment]
This was fixed in 17.0.0, forgot to close earlier.
