### ISSUE TITLE
contrib: can't find dep com.dwijnand:sbt-dynver

### ISSUE THREAD

**Issue by doofin** [raquo/Airstream#126]
Hi I got this while try to do sbt compile, it's weired that I didn't find this dep in plugins.sbt

`[error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-dynver;sbtVersion=1.0;scalaVersion=2.12:4.1.1`

**Comment by raquo** [comment]
sbt-dynver plugin is a dependency of sbt-ci-release that we use.

Does the error persist? Does the error output have any more details like
the URLs that SBT tried to download?

**Comment by doofin** [comment]
more details: 
`download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml
 download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml`

**Comment by raquo** [comment]
Seems like a problem with your network configuration, specifically, that your computer does not trust https://pki.goog/ which is who issued the SSL certificate of https://repo.scala-sbt.org. I can access both of these URLs fine from here.
