### ISSUE TITLE
Vars should be distinct-able

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#131]
We have `distinct*` operators for observables, but it would be nice if we also had similar operators for Var-s. They would work slightly differently in that they would prevent _writing_, not _reading_, of non-distinct values, to ensure that `myvar.now()` and `myvar.signal.now()` always return the same value. Currently to achieve such a filter, users need to put manual if conditions in front of Var updates, and that needs to happen at every write site, it can not be set as a policy on a Var.

Suggested syntax:

```scala
case class Foo(id: Int, text: String, size: Int)

val myVar0 = Var(initial = 42)

val myVar1 = Var(initial = 42).distinct
val myVar2 = Var(Foo(42, "hello")).distinctBy(_.id)
// and so on, matching Airstream distinct operators

// Usages (all of these go through one of the distinct filters we defined)
onClick.mapTo(1) --> myVar0.distinct
onClick.mapTo(1) --> myVar1
onClick.mapTo(Foo(42, "hello", 1)) --> myVar2
onClick.mapTo(1) --> myVar0.distinct.updater(_ + _) // first it computes the updated value, then it distinct-s that value against var's current value
```

To be clear, `Var(initial = 42).distinct` and similar creates a new lazy derived var that has a filter in its `zoomOut` method that only allows distinct updates through to its parent (which is `Var(initial = 42)`). In this particular snippet, the underlying `Var(initial = 42)` is discarded so there is no way to update the Var without the distinct filter, but e.g. in case of `onClick.mapTo(1) --> myVar0.distinct`, only this particular update path involves a distinct filter. Both use cases should work fine.

This looks like a flexible API with many uses requiring filtering Var updates. Some people may even prefer to use `.distinct` on Var-s wholesale when representing state. Unlike the problematic pre-15.0.0 approach with built-in `==` checks in vars and signals, this approach is opt-in, configurable, and targeted, similar to the `distinct` operators on observables, so all should be good.

Default behaviour of Var-s will remain the same, at least for the time being.

Prompted by @ivan-klass in https://github.com/raquo/Waypoint/issues/23

**Comment by ivan-klass** [comment]
Nice, thank you! The only naming nit-pick for `.distinct` - it might mean that it excludes values ever seen before, like
`List(1, 2, 2, 1).distinct` is `List(1, 2)` not `List(1, 2, 1)`, similarly for other collections, like `Vector`. But I'm not an expert in airstream, maybe it makes sense to be accordant to airstream naming rather then std lib here, it's up to you.

**Comment by raquo** [comment]
Hm. Indeed it seems that most streaming libraries have Airstream's version named `distinctUntilChanged`, whereas the `distinct` operator compares incoming values against _all_ previous values ever emitted by that observable.

I can definitely see the parallels to static collections, and often try to follow their naming, but sometimes the analogy breaks down, whether semantically or technically. I think the `distinct` operators are one of those cases, where seeing an observable as a single-value-that-updates is more useful than seeing it as a list-of-values-iterated-over-time (meaning that, we usually don't care about previous values, only the current value and the next value). This is especially true since `.distinct` is usually called on var-s and signals – observables that represent a piece of state changing in time.

I think the current semantics of our `distinct` operator serve us well, and deserve the shorter name. If we ever wanted / needed an operator that remembers the entire event history for distincting it, its name would need to reflect the accumulative nature of such a data structure (to make the memory use / memory management implications more apparent).
