### ISSUE TITLE
Implement EventStream.periodic

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#31]
Need a stream that emits values at an interval when it's active. it's possible to emulate with a DIY EventBus hack, but we should have a proper way to do this.

For API design, bare minimum is to emit Unit-s. But it might be quite cheap and useful to emit an index-like number instead. But then we need an option to reset the number on deactivation. Maybe make the counter a separate method.

Also, consider putting a limit on number of emitted values? But that will be more useful as a take() or until(), and well that's more of a https://github.com/raquo/Airstream/issues/23 thing, so maybe another day.

**Comment by swoogles** [comment]
Until this is implemented, could you post an example of the "EventBus hack"?

I finally decided to take the plunge and rewrite one of my projects with Laminar, but the first thing I need to do is trigger updates based on a clock tick. Basically-
```
val diffBus = new EventBus[Int] dom.window.setInterval(() => +1 --> diffBus, 10000)
```

**Comment by keynmol** [comment]
Following the conversation on [gitter](https://gitter.im/Laminar_/Lobby?at=5f564e54d4f0f55ebb0a0f7a), this seems to do the trick:

```scala
import com.raquo.laminar.api.L._
import org.scalajs.dom

val diffBus = new EventBus[Int]
dom.window.setInterval(() =>  diffBus.writer.onNext(scala.util.Random.nextInt), 1000)

val x = div(
  "Random number every second: ",
  child.text <-- diffBus.events.map(_.toString)
)

render(dom.document.getElementById("output"), x)
```

On ScalaFiddle: https://scalafiddle.io/sf/TbnkMEu/20

Seems like the simplest version of `EventStream.periodic` can be included in Airstream with caveats, as it's missing from the current docs almost completely. What do you think @raquo ?

**Comment by raquo** [comment]
Alright, I implemented a proper `EventStream.periodic` in Airstream. Will publish Airstream 0.10.1 with it soon.
