### ISSUE TITLE
Rename the concept of Transaction?

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#32]
I can never explain the meaning of a transaction without heavily referring the concept of propagation, and that tells me it's named incorrectly.

**Comment by cubuspl42** [comment]
I personally like the name `Transaction`, assuming the "technical" / "implementational" name is desired. Totally another topic is semantics vs implementation dispute, i.e. if it's good to name entities according to how they're implemented, as opposed to what they semantically mean. If more semantical name was desired, I'd go with "Moment" (probably inspired by Reactive Banana `Moment` monad).

**Comment by raquo** [comment]
Hm, Moment could actually be a decent name. Transaction in Airstream does sort of denote a specific moment in time.

**Comment by raquo** [comment]
Closing because I probably won't do it. Any incremental benefit does not seem to outweigh all the accumulated documentation / conversations / knowledge / etc. that the existing name benefits from.
