### ISSUE TITLE
Make topoRank field public

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#37]
`val topoRank` being `protected[airstream]` prevents users from extending `EventStream` or `Signal`, which is silly. The field should probably just be public.

EDIT: Is this actually true? I think I confused something. People are extending EventStream just fine it seems.

**Comment by narma** [comment]
It's actually true, I can make custom `Observable` only under `com.raquo.airstream` package, which is not good practice.

**Comment by raquo** [comment]
@narma I think you can overcome this issue by saying `override val topoRank` (not `override protected[airstream] val topoRank`). Seems to compile in 2.13 at least.

**Comment by raquo** [comment]
This is now documented in the docs, and with the new CustomSource API extending observables shouldn't be as common.

Also, for reading topoRank, there's a static `Observable.debugTopoRank(obs)` method now
