### ISSUE TITLE
JVM support

### ISSUE THREAD

**Issue by ajaychandran** [raquo/Airstream#44]
@raquo 
I would like to use Airstream to build Java FX applications.
Would you be open to cross publishing the library? I can submit a PR for the same.

**Comment by raquo** [comment]
Hey, one of the main reasons why Airstream is Scala.js-only is that Javascript's single-threaded environment considerably simplifies the API and implementation. Airstream uses a shared execution model where each observable can have some internal state (e.g. signal's current state) that is shared across all consumers of that observable.

I feel like supporting multithreading in a safe way would significantly complicate the implementation and probably require changes to Airstream's API, e.g. introducing stuff like ContextShift in FS2. What's your general plan for making Airstream thread-safe? Have you already thought about what the required changes would look like?

**Comment by ajaychandran** [comment]
> I feel like supporting multithreading in a safe way would significantly complicate the implementation and probably require changes to Airstream's API, e.g. introducing stuff like ContextShift in FS2

I agree.

Consider that
1. Most GUI runtimes like JavaFX are single threaded (like the JS runtime).
2. It should be possible to write a JavaFX library, similar to Scala DOM Types, that allows a developer to define a GUI in a declarative fashion.

The only missing piece is the data-binding framework, ie, Airstream.

If Airstream is ported to the JVM, _then users can build and bind GUIs in a decalarative fashion_.

The downside is that thread safety would be the users responsibility.
This may not be as bad as it seems on first glance; the library could provide a context aware `EventBus` for integrating external flows.
Also, timing related operations can be provided with FX animations.

I don't see a way to support multi-threading without introducing the `IO` monad.
Notably, a [solution](http://conal.net/papers/push-pull-frp/) was proposed by Conan Elliot and an attempt was made [here](https://github.com/scalaz/scalaz-reactive) (it was abandoned once the ZIO project moved).

I will explore these options and revisit the issue. Thank you for your consideration.

PS: Apologies for the late reply. I somehow missed the GitHub notification.
