### ISSUE TITLE
Airstream users, do you use emitOnce = true / false? How much and why?

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#58]
Question prompted by @ajaychandran's suggestion in another issue / pr to make this part of the API smoother.

The methods `EventStream.fromSeq`, `EventStream.fromValue` and `EventStream.fromTry` currently require you to specify this parameter. It's not optional because originally I wasn't sure what the default should be. My impression right now is that `emitOnce = false` is the most reasonable default.

So I'm inclined to add a default value for this paramtere, `emitOnce = false`, or, if people are actually using `emitOnce = true` for good reasons, to provide separate `fromSeqOnce` / `fromValueOnce` / `fromTryOnce` methods.

**Comment by raquo** [comment]
Link to original suggestion: https://github.com/raquo/Airstream/pull/54#issuecomment-752057883

**Comment by ngbinh** [comment]
I am slightly inclined to the the change with default parameter.
