### ISSUE TITLE
Var#zoom

### ISSUE THREAD

**Issue by raquo** [raquo/Airstream#63]
If we have a Var[A] we should be able to get Var[B] given A => B and B => A (or (B, A) => A for an "updater" version).

Implementation concerns:
- Timing of transactions must be consistent with "Var#update" and other methods
- For the purpose of `hasDuplicateTupleKeys` used in `Var.set` et al, the zoomed var should be considered to be the original underlying var (even after several zooming layers) to make sure we don't allow updating the same Var more than once in the same transaction.

**Comment by yurique** [comment]
I don't think I have ever needed this, but it looks like a nice feature to have.

**Comment by raquo** [comment]
Well, that turned out to be much harder than I thought, but I got it done.

I forgot that mapping state without an `owner` is [unsafe](https://github.com/raquo/Laminar/issues/37) in terms of memory management. You'll need an `owner` to create a DerivedVar. We'll have to see whether such an API will be annoying or not, but there's no other way around it if you want derived state available with Var's API. You could always just do a combination of `var.signal.map(...)` and `var.writer.contramap(...)` if Var API is not actually needed.
