### ISSUE TITLE
akka stream 's `Flow` like abstractions?

### ISSUE THREAD

**Issue by doofin** [raquo/Airstream#8]
`Flow` in akka stream allows processing pipelines  to be reused both for source and sink,which are correspondingly called events and writer in airstream. I have worked with akka-stream and really find this powerful,Can we implement this ? Would like to help

**Comment by raquo** [comment]
I'm not very familiar with Akka streams, could you explain more what you mean? How would that look in practice?

**Comment by doofin** [comment]
for example,we can concat `flow` to `sink`(writebus) or `source`(eventstream),and get the new sink / source ,and the common logic lives in `flow`,which can be shared by both `sink` and `source`

This might be worth to look at https://doc.akka.io/docs/akka/current/stream/stream-flows-and-basics.html

**Comment by raquo** [comment]
> for example,we can concat flow to sink(writebus) or source(eventstream),and get the new sink / source ,and the common logic lives in flow,which can be shared by both sink and source

> When I am creating a Eventbus , I might want to do some transformations ,but those are only supported with Eventstream

So basically for this to happen we'd need more transformation methods defined on `Observer` or `WriteBus`. Similar to how we have `contramap` and `filter`, but basically more of those.

I don't know if it would be possible to share a lot of code – or even signatures – for those transformations between observables and observers, as the semantics are too different in Airstream. Akka Streams do not have Ownership, Signals, or State, – just event streams which by themselves are easy to map to observers (which are essentially glorified callbacks). However, in Airstream we can't even have a `map` method defined on `Observable`, `LazyObservable` and `State` have to define and implement it separately. We'll face similar issues trying to find common ground between observers and observables.

If you need to apply stream-like transformations to a WriteBus, there's `writeBus.addSource(eventStream)`. It's a bit verbose but it does give you the ability to define your input in terms of streams (and thus allows for stream transformations).

**Comment by doofin** [comment]
Thanks!
